set -g mouse on
set -g status-fg white
set -g status-bg "colour238"
setw -g window-status-current-format "#[fg=colour255,bg=colour27] #I: #W #[default]"

# enable <C-Arrow> in vim on tmux
set -g default-terminal "xterm-256color"
setw -g xterm-keys on

# keybind
unbind C-b
set -g prefix M-q
# bind -n M-n new-window -c "#{pane_current_path}"
bind -n M-n run-shell 'tmux new-window "cd $(tmux display -p "\$TMUXPWD_#I"); exec $SHELL"'
bind -n M-, previous-window
bind -n M-. next-window
bind -n M-^ run-shell 'tmux split-window -h "cd $(tmux display -p "\$TMUXPWD_#I"); exec $SHELL"'
bind -n M-- run-shell 'tmux split-window -v "cd $(tmux display -p "\$TMUXPWD_#I"); exec $SHELL"'
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-H resize-pane -L
bind -n M-J resize-pane -D
bind -n M-K resize-pane -U
bind -n M-L resize-pane -R
bind -n M-f resize-pane -Z
bind -n M-i copy-mode
bind -n M-v run "xsel -bo | tmux load-buffer - && tmux paste-buffer"

bind k confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# set copy-mode in order to copy until under the caret
setw -g mode-keys vi
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -bi"
